repos:

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.2.8
  hooks:
    - id: add-license-headers
      args:
      - --start_year=2023

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.2
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
    exclude: >
        (?x)^(
            .*\.etp|
            .*\.vsw|
            .*\.scade|
            .*\.xscade|
            .*\.sct
        )$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace
    exclude: (?x)^(.*\.tot)$
