/* generated by SCADE Suite-Display Extension (WUX 2.0.dev0) */

/* SCADE Suite contexts */
#include "wuxctxModel.h"

/* SCADE Display includes */
#include <malloc.h>
#include "sdy/sdy_events.h"
#include "sdy/SDY1_Interface.h"

#include "WuxSdyExt.h"

/* SCADE Display init */
#ifdef WUX_DISPLAY_AS_BUFFERS
static WuxSdyScreen _screens[1];

int WuxSdyGetScreenCount()
{
    return 1;
}

const WuxSdyScreen* WuxSdyGetScreen(int index)
{
    return index >= 0 && index < 1 ? &_screens[index] : NULL;
}

void WuxSdyInit()
{
    /* Init of SDY1_Interface */
    _screens[0].name = "Interface";
    _screens[0].width = SDY1_Interface__screen_width();
    _screens[0].height = SDY1_Interface__screen_height();
    _screens[0].buffer = SDY1_Interface__init_buffer();
    _screens[0].size = _screens[0].width * _screens[0].height * 4;
}
#else
void WuxSdyInit()
{
    /* Init of SDY1_Interface */
    SDY1_Interface__init();
}
#endif /* WUX_DISPLAY_AS_BUFFERS */

/* SCADE Display cycle */
void WuxSdyDraw()
{
    /* Draw of SDY1_Interface */
    SDY1_Interface__draw();
}

/* Connections Suite => Display */
void WuxSdySetInputs()
{
    SDY1_Interface__lockio();
    /* sdyOutPoint => inPoint */
    {
        SDY1_Interface_Point v;
        v.x = Wu_Ctx_Mapped_P.outC.sdyOutPoint.x;
        v.y = Wu_Ctx_Mapped_P.outC.sdyOutPoint.y;
        SDY1_Interface_symbology_layer_S_inPoint(SDY1_Interface_L_symbology_layer(), v);
    }
    /* sdyOutString => inString */
    {
        SDY1_Interface_String v;
        v.count = Wu_Ctx_Mapped_P.outC.sdyOutString.count;
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            v.buffer[i1] = Wu_Ctx_Mapped_P.outC.sdyOutString.buffer[i1];
        }
        SDY1_Interface_symbology_layer_S_inString(SDY1_Interface_L_symbology_layer(), v);
    }
    /* sdyOutLine => inLine */
    {
        SDY1_Interface_Line v;
        int i1;
        for (i1 = 0; i1 < 5; i1++) {
            v[i1].x = Wu_Ctx_Mapped_P.outC.sdyOutLine[i1].x;
            v[i1].y = Wu_Ctx_Mapped_P.outC.sdyOutLine[i1].y;
        }
        SDY1_Interface_symbology_layer_S_inLine(SDY1_Interface_L_symbology_layer(), v);
    }
    /* sdyOutMask => inMask */
    {
        SDY1_Interface_Bits v;
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            v[i1] = Wu_Ctx_Mapped_P.outC.sdyOutMask[i1];
        }
        SDY1_Interface_symbology_layer_S_inMask(SDY1_Interface_L_symbology_layer(), v);
    }
    /* sdyOutSpeed => inSpeed */
    SDY1_Interface_symbology_layer_S_inSpeed(SDY1_Interface_L_symbology_layer(), Wu_Ctx_Mapped_P.outC.sdyOutSpeed);
    /* sdyOutUInt8 => inUInt8 */
    SDY1_Interface_symbology_layer_S_inUInt8(SDY1_Interface_L_symbology_layer(), Wu_Ctx_Mapped_P.outC.sdyOutUInt8);
    /* sdyOutPartialLine3x => inPartialLine[2].x */
    kcg_assign(&SDY1_Interface_symbology_layer_G_inPartialLine(SDY1_Interface_L_symbology_layer())[2].x, &Wu_Ctx_Mapped_P.outC.sdyOutPartialLine3x, sizeof(Wu_Ctx_Mapped_P.outC.sdyOutPartialLine3x));
    /* sdyOutGroup => inGroup */
    {
        struct {SDY1_Interface_Speed _inSpeed; SDY1_Interface_Point _inPoint; SDY1_Interface_Bits _inBits;} v;
        v._inSpeed = Wu_Ctx_Mapped_P.outC.sdyOutGroup.speed;
        v._inPoint.x = Wu_Ctx_Mapped_P.outC.sdyOutGroup.point.x;
        v._inPoint.y = Wu_Ctx_Mapped_P.outC.sdyOutGroup.point.y;
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            v._inBits[i1] = Wu_Ctx_Mapped_P.outC.sdyOutGroup.bits[i1];
        }
        kcg_assign(&SDY1_Interface_L_symbology_layer()->_inSpeed, &v, sizeof(v));
    }
    /* sdyOutPartialLine1 => inPartialLine[0] */
    {
        SDY1_Interface_Point v;
        v.x = Wu_Ctx_Mapped_P.outC.sdyOutPartialLine1.x;
        v.y = Wu_Ctx_Mapped_P.outC.sdyOutPartialLine1.y;
        kcg_assign(&SDY1_Interface_symbology_layer_G_inPartialLine(SDY1_Interface_L_symbology_layer())[0], &v, sizeof(v));
    }
    /* sdyOutPartialLine[0] => inPartialLine1 */
    {
        SDY1_Interface_Point v;
        v.x = Wu_Ctx_Mapped_P.outC.sdyOutPartialLine[0].x;
        v.y = Wu_Ctx_Mapped_P.outC.sdyOutPartialLine[0].y;
        SDY1_Interface_symbology_layer_S_inPartialLine1(SDY1_Interface_L_symbology_layer(), v);
    }
    /* sdyOutPartialLine[2].x => inPartialLine3x */
    {
        SGLfloat v;
        v = Wu_Ctx_Mapped_P.outC.sdyOutPartialLine[2].x;
        SDY1_Interface_symbology_layer_S_inPartialLine3x(SDY1_Interface_L_symbology_layer(), v);
    }
    /* sdyOutFlag => inFlag */
    SDY1_Interface_symbology_layer_S_inFlag(SDY1_Interface_L_symbology_layer(), Wu_Ctx_Mapped_P.outC.sdyOutFlag);
    /* sdyOutAnonymousBits => inAnonymousBits */
    {
        SGLbool v[8];
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            v[i1] = Wu_Ctx_Mapped_P.outC.sdyOutAnonymousBits[i1];
        }
        SDY1_Interface_symbology_layer_S_inAnonymousBits(SDY1_Interface_L_symbology_layer(), v);
    }
    /* sdyOutAnonymousPoint => inAnonymousPoint */
    {
        struct {SGLfloat x; SGLfloat y;} v;
        v.x = Wu_Ctx_Mapped_P.outC.sdyOutAnonymousPoint.x;
        v.y = Wu_Ctx_Mapped_P.outC.sdyOutAnonymousPoint.y;
        SDY1_Interface_symbology_layer_S_inAnonymousPoint(SDY1_Interface_L_symbology_layer(), v);
    }
    /* status => status */
    SDY1_Interface_symbology_layer_S_status(SDY1_Interface_L_symbology_layer(), Wu_Ctx_Mapped_P.outC.status);
    SDY1_Interface__unlockio();
}

/* Connections Suite <= Display */
void WuxSdyGetOutputs()
{
    SDY1_Interface__lockio();
    /* sdyInLine <= outLine */
    {
        SDY1_Interface_Line v;
        kcg_assign(v, (SDY1_Interface_symbology_layer_G_outLine(SDY1_Interface_L_symbology_layer())), sizeof(v));
        int i1;
        for (i1 = 0; i1 < 5; i1++) {
            Wu_Ctx_Mapped_P.inC.sdyInLine[i1].x = v[i1].x;
            Wu_Ctx_Mapped_P.inC.sdyInLine[i1].y = v[i1].y;
        }
    }
    /* sdyInPoint <= outPoint */
    {
        SDY1_Interface_Point v;
        kcg_assign(&v, &(SDY1_Interface_symbology_layer_G_outPoint(SDY1_Interface_L_symbology_layer())), sizeof(v));
        Wu_Ctx_Mapped_P.inC.sdyInPoint.x = v.x;
        Wu_Ctx_Mapped_P.inC.sdyInPoint.y = v.y;
    }
    /* sdyInString <= outString */
    {
        SDY1_Interface_String v;
        kcg_assign(&v, &(SDY1_Interface_symbology_layer_G_outString(SDY1_Interface_L_symbology_layer())), sizeof(v));
        Wu_Ctx_Mapped_P.inC.sdyInString.count = v.count;
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            Wu_Ctx_Mapped_P.inC.sdyInString.buffer[i1] = v.buffer[i1];
        }
    }
    /* sdyInLine2Y <= outLine[2].y */
    {
        SGLfloat v;
        v = SDY1_Interface_symbology_layer_G_outLine(SDY1_Interface_L_symbology_layer())[2].y;
        Wu_Ctx_Mapped_P.inC.sdyInLine2Y = v;
    }
    /* sdyPointX <= outPoint.x */
    {
        SGLfloat v;
        v = SDY1_Interface_symbology_layer_G_outPoint(SDY1_Interface_L_symbology_layer()).x;
        sdyPointX = v;
    }
    /* sdyInPointX <= outPoint.x */
    {
        SGLfloat v;
        v = SDY1_Interface_symbology_layer_G_outPoint(SDY1_Interface_L_symbology_layer()).x;
        Wu_Ctx_Mapped_P.inC.sdyInPointX = v;
    }
    /* sdyInMask <= outMask */
    {
        SDY1_Interface_Bits v;
        kcg_assign(v, (SDY1_Interface_symbology_layer_G_outMask(SDY1_Interface_L_symbology_layer())), sizeof(v));
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            Wu_Ctx_Mapped_P.inC.sdyInMask[i1] = v[i1];
        }
    }
    /* sdyInSpeed <= outSpeed */
    {
        SGLfloat v;
        v = SDY1_Interface_symbology_layer_G_outSpeed(SDY1_Interface_L_symbology_layer());
        Wu_Ctx_Mapped_P.inC.sdyInSpeed = v;
    }
    /* sdyInUInt8 <= outUInt8 */
    {
        SGLuint8 v;
        v = SDY1_Interface_symbology_layer_G_outUInt8(SDY1_Interface_L_symbology_layer());
        Wu_Ctx_Mapped_P.inC.sdyInUInt8 = v;
    }
    /* sdyInPartialLine3x <= outPartialLine[2].x */
    {
        SGLfloat v;
        v = SDY1_Interface_symbology_layer_G_outPartialLine(SDY1_Interface_L_symbology_layer())[2].x;
        Wu_Ctx_Mapped_P.inC.sdyInPartialLine3x = v;
    }
    /* sdyInGroup <= outGroup */
    {
        SGLfloat v1;
        v1 = SDY1_Interface_symbology_layer_G__outSpeed(SDY1_Interface_L_symbology_layer());
        Wu_Ctx_Mapped_P.inC.sdyInGroup.speed = v1;
        SDY1_Interface_Point v2;
        kcg_assign(&v2, &SDY1_Interface_symbology_layer_G__outPoint(SDY1_Interface_L_symbology_layer()), sizeof(v2));
        Wu_Ctx_Mapped_P.inC.sdyInGroup.point.x = v2.x;
        Wu_Ctx_Mapped_P.inC.sdyInGroup.point.y = v2.y;
        SDY1_Interface_Bits v3;
        kcg_assign(v3, &SDY1_Interface_symbology_layer_G__outBits(SDY1_Interface_L_symbology_layer()), sizeof(v3));
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            Wu_Ctx_Mapped_P.inC.sdyInGroup.bits[i1] = v3[i1];
        }
    }
    /* sdyInPartialLine1 <= outPartialLine[0] */
    {
        SDY1_Interface_Point v;
        kcg_assign(&v, &(SDY1_Interface_symbology_layer_G_outPartialLine(SDY1_Interface_L_symbology_layer()))[0], sizeof(v));
        Wu_Ctx_Mapped_P.inC.sdyInPartialLine1.x = v.x;
        Wu_Ctx_Mapped_P.inC.sdyInPartialLine1.y = v.y;
    }
    /* sdyInPartialLine[0] <= outPartialLine1 */
    {
        SDY1_Interface_Point v;
        kcg_assign(&v, &(SDY1_Interface_symbology_layer_G_outPartialLine1(SDY1_Interface_L_symbology_layer())), sizeof(v));
        Wu_Ctx_Mapped_P.inC.sdyInPartialLine[0].x = v.x;
        Wu_Ctx_Mapped_P.inC.sdyInPartialLine[0].y = v.y;
    }
    /* sdyInPartialLine[2].x <= outPartialLine3x */
    {
        SGLfloat v;
        v = SDY1_Interface_symbology_layer_G_outPartialLine3x(SDY1_Interface_L_symbology_layer());
        Wu_Ctx_Mapped_P.inC.sdyInPartialLine[2].x = v;
    }
    /* sdyInFlag <= outFlag */
    {
        SGLlong v;
        v = SDY1_Interface_symbology_layer_G_outFlag(SDY1_Interface_L_symbology_layer());
        Wu_Ctx_Mapped_P.inC.sdyInFlag = v;
    }
    /* sdyInAnonymousBits <= outAnonymousBits */
    {
        SGLbool v[8];
        kcg_assign(v, (SDY1_Interface_symbology_layer_G_outAnonymousBits(SDY1_Interface_L_symbology_layer())), sizeof(v));
        int i1;
        for (i1 = 0; i1 < 8; i1++) {
            Wu_Ctx_Mapped_P.inC.sdyInAnonymousBits[i1] = v[i1];
        }
    }
    /* sdyInAnonymousPoint <= outAnonymousPoint */
    {
        struct {SGLfloat x; SGLfloat y;} v;
        kcg_assign(&v, &(SDY1_Interface_symbology_layer_G_outAnonymousPoint(SDY1_Interface_L_symbology_layer())), sizeof(v));
        Wu_Ctx_Mapped_P.inC.sdyInAnonymousPoint.x = v.x;
        Wu_Ctx_Mapped_P.inC.sdyInAnonymousPoint.y = v.y;
    }
    SDY1_Interface__unlockio();
}

/* SCADE Display cancelled */
int WuxSdyCancelled()
{
    if (SDY1_Interface__cancelled()) return 1;
    return 0;
}

/* end of file */
