# Copyright (C) 2023 - 2024 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Utility classes and functions for developing wrappers."""

from pathlib import Path
from typing import List, Optional

from scade.code.suite.mapping.c import MappingFile
import scade.code.suite.sctoc as sctoc
from scade.code.suite.wrapgen.c import InterfacePrinter
from scade.code.suite.wrapgen.model import MappingHelpers

# globals
# context
mf: Optional[MappingFile] = None
mh: Optional[MappingHelpers] = None
ips: list[InterfacePrinter] = []


# generated C files, for makefile
_sources: set[str] = set()
# build
_libraries: set[str] = set()
_includes: set[str] = set()
_definitions: set[str] = set()


# store the declared source files for backward compatibility
# and prevent adding the same source twice to sctoc
def add_sources(paths: list[Path]):
    """TODO."""
    global _sources
    paths = {_.as_posix() for _ in paths}
    sctoc.add_c_files(list(paths - _sources), False, 'WUX')
    _sources |= paths


# store the declared include paths for backward compatibility
# and prevent adding the same include twice to sctoc
def add_includes(paths: List[Path]):
    """TODO."""
    global _includes
    paths = {_.as_posix() for _ in paths}
    sctoc.add_include_files(list(paths - _includes), False)
    _includes |= paths


# store the declared libraries for backward compatibility
# and prevent adding the same library twice to sctoc
def add_libraries(paths: List[Path]):
    """TODO."""
    global _libraries
    paths = {_.as_posix() for _ in paths}
    sctoc.add_obj_files(list(paths - _libraries), False)
    _libraries |= paths


# prevent adding the preprocessor definition twice to sctoc
def add_definitions(*definitions: str):
    """TODO."""
    global _definitions
    definitions = {_ for _ in definitions}
    sctoc.add_preprocessor_definitions(*(definitions - _definitions))
    _definitions |= definitions


def writeln(f, nbtabs: int = 0, text: str = ''):
    """TODO."""
    f.write('    ' * nbtabs)
    f.write(text)
    f.write('\n')


def write_indent(f, tab: str, text: str):
    """TODO."""
    if text != '':
        f.write(tab)
        f.write(('\n' + tab).join(text.strip('\n').split('\n')))
        f.write('\n')


def gen_start_protect(f, name: str):
    """TODO."""
    macro = '_' + name.replace('.', '_').upper() + '_'
    writeln(f, 0, '#ifndef {0}\n#define {0}'.format(macro))
    writeln(f)


def gen_end_protect(f, name: str):
    """TODO."""
    macro = '_' + name.replace('.', '_').upper() + '_'
    writeln(f, 0, '#endif /* {0} */'.format(macro))
    writeln(f)


def gen_header(f, banner: str, start_comment: str = '/* ', end_comment: str = ' */'):
    """TODO."""
    writeln(f, 0, '{1}generated by {0}{2}'.format(banner, start_comment, end_comment))
    writeln(f)


def gen_footer(f):
    """TODO."""
    writeln(f, 0, '/* end of file */')


def gen_includes(f, files: List[str]):
    """TODO."""
    writeln(f, 0, '/* includes */')
    for file in files:
        writeln(f, 0, '#include "%s"' % file)
    writeln(f)
